export const languages = [
    // most commun programming languages
    { value: "All", label: "All Languages" },
    { value: "JavaScript", label: "JavaScript" },
    { value: "TypeScript", label: "TypeScript" },
    { value: "Python", label: "Python" },
    { value: "Java", label: "Java" },
    { value: "C#", label: "C#" },
    { value: "C++", label: "C++" },
    { value: "C", label: "C" },
    { value: "Ruby", label: "Ruby" },
    { value: "Go", label: "Go" },
    { value: "Rust", label: "Rust" },
    { value: "PHP", label: "PHP" },
    { value: "Kotlin", label: "Kotlin" },
    { value: "Swift", label: "Swift" },
    { value: "Dart", label: "Dart" },
    { value: "MATLAB", label: "MATLAB" },
    { value: "Scala", label: "Scala" },
    { value: "R", label: "R" },
    { value: "Shell", label: "Shell Scripting" },
    { value: "Bash", label: "Bash" },
    { value: "Perl", label: "Perl" },
    { value: "Elixir", label: "Elixir" },
    { value: "Haskell", label: "Haskell" },
    { value: "Lua", label: "Lua" },
    { value: "Objective-C", label: "Objective-C" },
  
    // frameworks and libraries of frontend
    { value: "Vite", label: "Vite" },
    { value: "Html", label: "Html" },
    { value: "React", label: "React" },
    { value: "Next.js", label: "Next.js" },
    { value: "Vue.js", label: "Vue.js" },
    { value: "Nuxt.js", label: "Nuxt.js" },
    { value: "Angular", label: "Angular" },
    { value: "Svelte", label: "Svelte" },
    { value: "Solid.js", label: "Solid.js" },
    { value: "Preact", label: "Preact" },
    { value: "Gatsby", label: "Gatsby" },
  
    // frameworks and libraries of backend
    { value: "Node.js", label: "Node.js" },
    { value: "Express.js", label: "Express.js" },
    { value: "Nest.js", label: "Nest.js" },
    { value: "Adonis.js", label: "Adonis.js" },
    { value: "Fastify", label: "Fastify" },
    { value: "Django", label: "Django" },
    { value: "Flask", label: "Flask" },
    { value: "Spring Boot", label: "Spring Boot" },
    { value: "ASP.NET", label: "ASP.NET" },
    { value: "Ruby on Rails", label: "Ruby on Rails" },
    { value: "Laravel", label: "Laravel" },
    { value: "CodeIgniter", label: "CodeIgniter" },
    { value: "Phoenix", label: "Phoenix (Elixir)" },
  
    // most commun databases
    { value: "MySQL", label: "MySQL" },
    { value: "PostgreSQL", label: "PostgreSQL" },
    { value: "MongoDB", label: "MongoDB" },
    { value: "Firebase", label: "Firebase" },
    { value: "Supabase", label: "Supabase" },
    { value: "Redis", label: "Redis" },
    { value: "SQLite", label: "SQLite" },
    { value: "Cassandra", label: "Cassandra" },
    { value: "MariaDB", label: "MariaDB" },
    { value: "Oracle", label: "Oracle" },
    { value: "Microsoft SQL Server", label: "Microsoft SQL Server" },
    { value: "Neo4j", label: "Neo4j" },
    { value: "DynamoDB", label: "DynamoDB" },
  
    // devops
    { value: "Docker", label: "Docker" },
    { value: "Kubernetes", label: "Kubernetes" },
    { value: "Jenkins", label: "Jenkins" },
    { value: "GitHub Actions", label: "GitHub Actions" },
    { value: "GitLab CI/CD", label: "GitLab CI/CD" },
    { value: "CircleCI", label: "CircleCI" },
    { value: "AWS", label: "AWS" },
    { value: "Azure", label: "Azure" },
    { value: "Google Cloud", label: "Google Cloud" },
    { value: "Terraform", label: "Terraform" },
    { value: "Ansible", label: "Ansible" },
  
    // machine learning and data science technologies
    { value: "TensorFlow", label: "TensorFlow" },
    { value: "Keras", label: "Keras" },
    { value: "PyTorch", label: "PyTorch" },
    { value: "Scikit-Learn", label: "Scikit-Learn" },
    { value: "NumPy", label: "NumPy" },
    { value: "Pandas", label: "Pandas" },
    { value: "Matplotlib", label: "Matplotlib" },
    { value: "Seaborn", label: "Seaborn" },
    { value: "OpenCV", label: "OpenCV" },
    { value: "NLTK", label: "NLTK" },
    { value: "HuggingFace", label: "HuggingFace" },
  
    // mobile development
    { value: "React Native", label: "React Native" },
    { value: "Flutter", label: "Flutter" },
    { value: "Ionic", label: "Ionic" },
  
    // UI/UX tools and libraries
    { value: "CSS", label: "CSS" },
    { value: "Tailwind CSS", label: "Tailwind CSS" },
    { value: "Bootstrap", label: "Bootstrap" },
    { value: "Material UI", label: "Material UI" },
    { value: "Chakra UI", label: "Chakra UI" },
    { value: "Shadcn UI", label: "Shadcn UI" },
    { value: "Ant Design", label: "Ant Design" },
    { value: "Foundation", label: "Foundation" },

  ];
  